version: "3.8"
services:
  app:
    build: .
    container_name: ideh
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:admin@localhost/user_db
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: user_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
