"""Initial migration.

Revision ID: 368958fe30fb
Revises: 
Create Date: 2024-11-21 20:37:39.153219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '368958fe30fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scraped_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by_user_id', sa.String(length=50), nullable=False),
    sa.Column('url', sa.String(length=2083), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=250), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('page_content_type', sa.String(length=100), nullable=True),
    sa.Column('contact', sa.String(length=250), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraped_data')
    # ### end Alembic commands ###
